[[categories]]
name = "プログラミング系"
key = "program"
  [[categories.groups]]
    name = "無線研究部"
    key = "ja1yad"
    desc = "プログラミングやアマチュア無線に取り組んでいます"
    [categories.groups.details]
      desc = [
        "<a href=\"https://musenken.net\" target=\"_blank\" rel=\"noopener noreferrer\">無線研公式ホームページ</a>",
        "<a href=\"https://twitter.com/ja1yad\" target=\"_blank\" rel=\"noopener noreferrer\">公式Twitter</a>"
      ]
      img = []
      slide = [
        "./images/ja1yad/1.png",
        "./images/ja1yad/2.png",
        "./images/ja1yad/3.png",
        "./images/ja1yad/4.png",
        "./images/ja1yad/5.png",
        "./images/ja1yad/6.png",
        "./images/ja1yad/7.png",
        "./images/ja1yad/8.png",
        "./images/ja1yad/9.png",
        "./images/ja1yad/10.png",
        "./images/ja1yad/11.png",
        "./images/ja1yad/12.png",
        "./images/ja1yad/13.png",
        "./images/ja1yad/14.png",
        "./images/ja1yad/15.png",
        "./images/ja1yad/16.png",
        "./images/ja1yad/17.png",
        "./images/ja1yad/18.png",
      ]
[[categories]]
name = "バイオものづくり系"
key = "bio"
  [[categories.groups]]
    name = "iGEM TokyoTech"
    key = "igem"
    desc = "合成生物学の応用法を探求する国際大会に出場してます"
    [categories.groups.details]
      desc = [
        "私達iGEM TokyoTechは、iGEMという合成生物学の国際大会に出席し、結果を残すことを目的に研究を行うサークルです。",
        "iGEMは、遺伝子工学実験によりユニークな遺伝子組み換え生物を作り出し、その機能や独創性、有意性を競う大会です。合成生物学とは、生物の遺伝子を改変することで人々にとって有益な産物を作ることを目指す生物学分野です。",
        "難しいように聞こえますが、実際には高校生でも扱える内容が多く、学部生だけで研究を進めています！",
        "<p>主な活動内容</p><ul><li>遺伝工学実験</li><li>プログラミングでのシミュレーション</li><li>英語でのプレゼンテーション発表準備</li></ul>",
        "新歓用メールアドレス：<a href=\"mailto:igem2021tokyotech@gmail.com\" target=\"_blank\" rel=\"noopener noreferrer\">igem2021tokyotech@gmail.com</a>",
        "公式Twitter：<a href=\"https://twitter.com/igem_tokyotech/\" target=\"_blank\" rel=\"noopener noreferrer\">@igem_tokyotech</a>",
        "<a href=\"https://igemtitech.wixsite.com/igem-tokyotech/\" target=\"_blank\" rel=\"noopener noreferrer\">公式サイト</a>",
        "サークルに参加したい方はもちろん、活動を見学したい方、質問がある方は気軽に公式Twitterまたは新歓用メールアドレスにご連絡ください！"
      ]
      img = []
      slide = [
        "./images/igem/1.png",
        "./images/igem/2.png",
        "./images/igem/3.png",
        "./images/igem/4.png",
        "./images/igem/5.png",
        "./images/igem/6.png",
        "./images/igem/7.png",
        "./images/igem/8.png",
        "./images/igem/9.png",
        "./images/igem/10.png",
        "./images/igem/11.png",
        "./images/igem/12.png",
        "./images/igem/13.png"
      ]
  